ControlPanel/Models/Report.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace ControlPanel.Models
{
    public class Report
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Требуется поле Логин")]
        [Display(Name = "Отчет")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Требуется начальный период")]
        [Display(Name ="C:")]        
        public string DateFrom { get; set; }

        [Required(ErrorMessage = "Требуется конечный период")]
        [Display(Name = "По:")]        
        public string DateTo { get; set; }
    }
}

ControlPanel/Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using System.Text;
using ControlPanel.Models;
using ControlPanel.Abstract;
using NLog;
using System.Threading.Tasks;
using System.Runtime.Serialization.Formatters.Binary;
using CsvHelper;
using CsvHelper.Configuration;
using System.Globalization;
using ControlPanel.ViewModels;
using System.Net;
using ControlPanel.Filters;

namespace ControlPanel.Controllers
{
    [Authorize]
    [ErrorLogger]
    [ActionLogger]
    public class ReportsController : Controller
    {
        IAgentRepository agentRpository;
        ISkillRepository skillRepository;
        private static Logger logger = LogManager.GetCurrentClassLogger();

        public ReportsController(IAgentRepository agentRepository, ISkillRepository skillRepository)
        {
            this.agentRpository = agentRepository;
            this.skillRepository = skillRepository;
        }

        // GET: Reports
        public ActionResult Index()
        {
            string[] reports = new string[] { "AgentReport", "SkillReport" };
            ReportsIndexViewModel reportsIndexViewModel = new ReportsIndexViewModel
            {
                ReportNames = new SelectList(reports),
                Report = new Report 
                { 
                    Name = "SkillReport", 
                    DateFrom= DateTime.Now.AddDays(-1).ToString("yyyy-MM-dd") + "T" + DateTime.Now.AddDays(-1).ToString("HH:mm"),
                    DateTo = DateTime.Now.ToString("yyyy-MM-dd")+"T"+ DateTime.Now.ToString("HH:mm") 
                }
            };
            return View(reportsIndexViewModel);
        }

        [HttpPost]
        public async Task<ActionResult> GetReport(string actionName, [Bind] Report report)
        {
            if(actionName.ToLower()=="preview"&& report.Name == "AgentReport")
            {
                var agentsForReport = await agentRpository.GetAgentsIncludeGroupAsync();
                agentsForReport = agentsForReport.Take(10).OrderBy(agent => agent.Login).ToList();
                return View("GetAgentReport", agentsForReport);
            }
            if(actionName.ToLower() == "preview" && report.Name =="SkillReport")
            {
                var skillsForReport = skillRepository.GetSkillsFromSqlQuery();
                skillsForReport = skillsForReport.Take(10).OrderBy(skill => skill.Key).ToList();
                return View("GetSkillReport", skillsForReport);
            }

            var csvFilePath=await GetCsvFilePath(report);
            string fileType = "application/csv";
            string fileName = $"{report.Name}_{report.DateFrom}_{report.DateTo}.csv";
            return File(csvFilePath, fileType, fileName);
        }

        private async Task<string> GetCsvFilePath(Report report)
        {
            string csvFilePath = null;
            switch (report.Name)
            {
                case "AgentReport":
                    var agents = await agentRpository.GetAgentsAsync();
                    List<AgentReportViewModel> agentsForReport = agents
                        .Select(agent => new AgentReportViewModel
                        {
                            Id = agent.Id,
                            Name = agent.Name,
                            Login = agent.Login,
                            WorkloadMaxContactsCount = agent.WorkloadMaxContactsCount,
                            IsAlgorithmAllowServiceLevel = agent.IsAlgorithmAllowServiceLevel,
                            Algorithm = agent.Algorithm
                        }
                        ).ToList();

                    csvFilePath = CreateCsvReport<AgentReportViewModel>(report, agentsForReport);
                    break;

                case "SkillReport":
                    //var skillsForReport = await skillRepository.GetSkillsAsync();
                    var skills = skillRepository.GetSkillsFromSqlQuery();
                    List<SkillReportViewModel> skillsForReport = skills
                        .Select(skill => new SkillReportViewModel
                        {
                            Id = skill.Id,
                            Key = skill.Key,
                            Name = skill.Name,
                            Algorithm = skill.Algorithm
                        }
                        ).ToList();
                    csvFilePath = CreateCsvReport<SkillReportViewModel>(report, skillsForReport);
                    break;
                default:
                    break;                    
            }
            return csvFilePath;
        }

        private string CreateCsvReport<T>(Report report, List<T> reportData)
        {
            string pathCsvFile = $@"C:\Users\Edegt\AppData\Roaming\ControlPanel\{report.Name}.csv";
            CsvConfiguration configuration = new CsvConfiguration(CultureInfo.CurrentCulture);
            configuration.Encoding = Encoding.GetEncoding(1251);
            using (StreamWriter streamWriter = new StreamWriter(pathCsvFile))
            {
                using (CsvWriter csvWriter = new CsvWriter(streamWriter, configuration))
                {
                    csvWriter.Configuration.Delimiter = ";";
                    csvWriter.WriteRecords(reportData);
                }
            }
            return pathCsvFile;
        }
    }
}

ControlPanel/Views/Reports/GetAgentReport.cshtml
@using ControlPanel.Models
@model List<Agent>

<h2>Отчет по агентам</h2>
<br/>

<table class="table table-striped">
	<tr>
		<th>
			@Html.DisplayNameFor(model => model.FirstOrDefault().Name)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.FirstOrDefault().Login)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.FirstOrDefault().Algorithm)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.FirstOrDefault().WorkloadMaxContactsCount)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.FirstOrDefault().IsAlgorithmAllowServiceLevel)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.FirstOrDefault().Group.Name)
		</th>
	</tr>

	@foreach (var agent in Model)
	{
		<tr>
			<td>
				@Html.DisplayFor(model => agent.Name)
			</td>
			<td>
				@Html.DisplayFor(model => agent.Login)
			</td>
			<td>
				@Html.DisplayFor(model => agent.AlgorithmName)
			</td>
			<td>
				@Html.DisplayFor(model => agent.WorkloadMaxContactsCount)
			</td>
			<td>
				@Html.DisplayFor(model => agent.IsAlgorithmAllowServiceLevel)
			</td>
			<td>
				@Html.DisplayFor(model => agent.Group.Name)
			</td>
		</tr>
	}
</table>

ControlPanel/Views/Reports/GetSkillReport.cshtml
@using ControlPanel.Models
@model List<Skill>

<h2>Отчет по навыкам</h2>
<br />

<table class="table table-striped">
	<tr>
		<th>
			@Html.DisplayNameFor(model => model.FirstOrDefault().Name)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.FirstOrDefault().Key)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.FirstOrDefault().Algorithm)
		</th>
	</tr>

	@foreach (var skill in Model)
	{
		<tr>
			<td>
				@Html.DisplayFor(model => skill.Name)
			</td>
			<td>
				@Html.DisplayFor(model => skill.Key)
			</td>
			<td>
				@Html.DisplayFor(model => skill.AlgorithmName)
			</td>
		</tr>
	}
</table>

ControlPanel/Views/Reports/Index.cshtml
@model ControlPanel.ViewModels.ReportsIndexViewModel


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
	<h2>Отчеты в системе</h2>

	@using (Html.BeginForm("GetReport", "Reports"))
	{
		<div class="form-horizontal">
			<hr />
			@Html.ValidationSummary(true, "", new { @class = "text-danger" })
			<div class="form-group">
				@Html.LabelFor(model => model.Report.Name, htmlAttributes: new { @class = "control-label col-md-3" })
				<div class="col-md-3">
					@Html.DropDownListFor(model => model.Report.Name, Model.ReportNames as SelectList, htmlAttributes: new { @class = "form-control" })
					@Html.ValidationMessageFor(model => model.Report.Name, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				@Html.LabelFor(model => model.Report.DateFrom, htmlAttributes: new { @class = "control-label col-md-3" })
				<div class="col-md-3">
					@Html.EditorFor(model => model.Report.DateFrom, new { htmlAttributes = new { @class = "form-control", type = "datetime-local" } })
					@Html.ValidationMessageFor(model => model.Report.DateFrom, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				@Html.LabelFor(model => model.Report.DateTo, htmlAttributes: new { @class = "control-label col-md-3" })
				<div class="col-md-3">
					@Html.EditorFor(model => model.Report.DateTo, new { htmlAttributes = new { @class = "form-control", type = "datetime-local" } })
					@Html.ValidationMessageFor(model => model.Report.DateTo, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				<div class="col-md-offset-3 col-md-10">
					@*<input type="submit" value="Download" name="actionName" class="btn btn-default" />
						<input type="submit" value="Preview" name="actionName" class="btn btn-primary"/>*@

					<button name="actionName" class="btn btn-default" value="Download"><i class="fa fa-download"></i> Скачать</button>
					<button name="actionName" class="btn btn-primary" value="Preview">Просмотр</button>
				</div>
			</div>
		</div>
	}
</body>
</html>